GET http://localhost:7000/api/locations

###
POST http://localhost:7000/api/locations
Content-Type: application/json

{
  "name": "New Planet3",
  "type": "Planet",
  "dimension": "dimension"
}

###
POST http://localhost:7000/api/characters
Content-Type: application/json

{
    "name": "Béla",
    "status": "ember",
    "species": "String",
    "type" : "ams",
    "gender": "male",
    "location": {"name": "location"}
}
